### ISSUE TITLE
go test failed bson_test

### ISSUE THREAD

**Issue by lsytj0413** [siddontang/go#10]
### Description
go test failed bson_test

### Reproduction guide
1. clone repo
2. run go test ./...

### Observed behaviour

`----------------------------------------------------------------------
FAIL: bson_test.go:597: S.TestMarshalErrorItems

bson_test.go:600:
    c.Assert(err, ErrorMatches, item.data)
... error string = "Attempted to marshal Raw kind 10 as a document"
... regex string = "Attempted to unmarshal Raw kind 10 as a document"

----------------------------------------------------------------------
FAIL: bson_test.go:1429: S.TestObjectIdJSONUnmarshalingError

bson_test.go:1432:
    c.Assert(err, ErrorMatches, `Invalid ObjectId in JSON: "4d88e15b60f486e428412dc9A"`)
... error string = "invalid ObjectId in JSON: \"4d88e15b60f486e428412dc9A\""
... regex string = "Invalid ObjectId in JSON: \"4d88e15b60f486e428412dc9A\""`

### Expected behaviour: 
test passed.

### System Info 
OS: gnu/linux
golang: go version go1.9.2 linux/amd64

**Comment by siddontang** [comment]
Hi @lsytj0413 

Can you help me fix it? maybe upgrading the bson implementation from https://github.com/go-mgo/mgo/tree/v2/bson?

**Comment by lsytj0413** [comment]
Is your code just copied from mgo/bson pacakge? can i just replace it with the new version?

**Comment by lsytj0413** [comment]
#11

**Comment by siddontang** [comment]
Thanks @lsytj0413
